/*
how to parse json?

for some sku num, which is a key in a dictionary representing a database. retrieve the key safely.
If the key exists
	find the first 10 values of keys that are most similar to the input key.
	or find the best matches of all the possible matches.
	*speed ? divide the db into sections? and search in parallel for good matches? then
	sort good matches?

	what is a weight and how to show it,

	def weight
	def match
*/
